import _curry2 from './internal/_curry2'

/**
 * Sorts the list according to the supplied function.
 *
 * @sig Ord b => (a -> b) -> [a] -> [a]
 * @param {Function} fn
 * @param {Array} list
 * @return {Array} A new list sorted by the keys generated by `fn`
 * @example
 *
 * import { sortBy, prop } from 'funale'
 *
 * const sortByFirstItem = sortBy(prop(0))
 * const pairs = [[-1, 1], [-2, 2], [-3, 3]]
 * sortByFirstItem(pairs) // [[-3, 3], [-2, 2], [-1, 1]]
 */
const sortBy = _curry2((fn, list) => {
  return Array.prototype.slice.call(list, 0).sort((a, b) => {
    const aa = fn(a)
    const bb = fn(b)
    return aa < bb ? -1 : aa > bb ? 1 : 0
  })
})
export default sortBy
